---

- name: configure interface on Arista switch
  hosts: arista

  tasks:
    - name: set secondary int eth6 description
      eos_interface: name=Ethernet6 description="*** IN USE ***"
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

    - name: configure interface with vlan
      eos_switchport: name=Ethernet6 mode=access access_vlan=777
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

