---

- name: cleanup Arista configs
  hosts: arista

  tasks:
    - name: remove trunk config
      eos_switchport: name=Ethernet6 mode=access access_vlan=1 trunk_allowed_vlans=1-4094 trunk_native_vlan=1
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

    - name: reset interface description
      eos_interface: name=Ethernet6 description=""
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

    - name: remove daveg vlans
      eos_vlan: name={{ item.name }} vlanid={{ item.vlanid }} state=absent
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

      with_items:
        - { name: daveg_vlan755, vlanid: 755 }
        - { name: daveg_vlan766, vlanid: 766 }
        - { name: daveg_vlan777, vlanid: 777 }
